import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs'
import { dark } from '@clerk/themes';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
        variables: {
          colorPrimary: "#6366f1", 
          colorBackground: "#09090b", 
          colorText: "#f4f4f5", 
          colorInputBackground: "#18181b", 
          colorInputText: "#ffffff",
          borderRadius: "0.75rem",
        },
        elements: {
          card: "bg-zinc-950 border border-white/10 shadow-2xl backdrop-blur-xl",
          headerTitle: "text-white font-bold tracking-tight",
          headerSubtitle: "text-zinc-400",
          socialButtonsBlockButton: "bg-white text-black hover:bg-zinc-200 border-0 transition-colors",
          socialButtonsBlockButtonText: "font-medium",
          dividerLine: "bg-zinc-800",
          dividerText: "text-zinc-500 uppercase text-[10px] tracking-widest",
          formFieldLabel: "text-xs font-medium text-zinc-400 ml-1",
          formFieldInput: "bg-zinc-900/50 border border-white/10 text-white placeholder:text-zinc-600 rounded-lg focus:border-indigo-500/50 focus:ring-2 focus:ring-indigo-500/20 transition-all",
          formButtonPrimary: "bg-gradient-to-r from-indigo-600 to-indigo-500 hover:from-indigo-500 hover:to-indigo-400 text-white font-medium border-0 shadow-lg shadow-indigo-500/20 transition-all normal-case",
          footerActionLink: "text-indigo-400 hover:text-indigo-300 font-medium",
          footer: "border-t border-white/5 bg-zinc-950/50" 
        }
      }}
    >
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {/* <header className="flex justify-end items-center p-4 gap-4 h-16">
          </header> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
